// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Q6ZDn5MwOOGeaVVHD3xJ6wn1uqzTYX8',
    appId: '1:65658599270:web:8be670d96b581a437c3aa7',
    messagingSenderId: '65658599270',
    projectId: 'bloc-firebase-practice',
    authDomain: 'bloc-firebase-practice.firebaseapp.com',
    storageBucket: 'bloc-firebase-practice.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBREXr7yeX4krlSM7lQ5I-rTml4vLUHQzc',
    appId: '1:65658599270:android:a378bdec92b43fd17c3aa7',
    messagingSenderId: '65658599270',
    projectId: 'bloc-firebase-practice',
    storageBucket: 'bloc-firebase-practice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKLXD1D-jNK6htQJfk5CraBkZmN18TWG0',
    appId: '1:65658599270:ios:46724c29c88fe0af7c3aa7',
    messagingSenderId: '65658599270',
    projectId: 'bloc-firebase-practice',
    storageBucket: 'bloc-firebase-practice.appspot.com',
    iosClientId: '65658599270-7sihhgana4umga5li55crbemm04jieeu.apps.googleusercontent.com',
    iosBundleId: 'com.aizazhaider.bloc',
  );
}
